export const GET_POST_REQUESTING = "GET_POST_REQUESTING";
export const GET_POST_REQUESTED = "GET_POST_REQUESTED";
export const GET_POST_REJECTED = "GET_POST_REJECTED";
export const GET_POST_FULFILLED = "GET_POST_FULFILLED";
export const HIDE_WARNING = "HIDE_WARNING";
export const GET_POST_ADDED_ACTION = "GET_POST_ADDED_ACTION";
export const WATCH_GUEST_ADDED_EVENT = "WATCH_GUEST_ADDED_EVENT";

export const CREATE_POST_REQUESTING = 'CREATE_POST_REQUESTING';
export const CREATE_POST_REQUESTED = 'CREATE_POST_REQUESTED';
export const CREATE_POST_REJECTED = 'CREATE_POST_REJECTED';
export const CREATE_POST_FULFILLED = 'CREATE_POST_FULFILLED';

export const AUTH_LOGIN_REQUESTING = 'AUTH_LOGIN_REQUESTING';
export const AUTH_LOGIN_FULFILLED = 'AUTH_LOGIN_FULFILLED';
export const AUTH_LOGIN_REJECTED = 'AUTH_LOGIN_REJECTED';
export const AUTH_REGISTER_REQUESTING = 'AUTH_REGISTER_REQUESTING';
export const AUTH_REGISTER_REQUESTED = 'AUTH_REGISTER_REQUESTED';
export const AUTH_REGISTER_REJECTED = 'AUTH_REGISTER_REJECTED';
export const AUTH_REGISTER_FULFILLED = "AUTH_REGISTER_FULFILLED";
export const AUTH_LOGOUT_REQUESTING = 'AUTH_LOGOUT_REQUESTING';
export const AUTH_LOGOUT_FULFILLED = 'AUTH_LOGOUT_FULFILLED';
export const AUTH_LOGOUT_REJECTED = 'AUTH_LOGOUT_REJECTED';
