export const GET_POST_REQUESTING = "GET_POST_REQUESTING";
export const GET_POST_REQUESTED = "GET_POST_REQUESTED";
export const GET_POST_REJECTED = "GET_POST_REJECTED";
export const GET_POST_FULFILLED = "GET_POST_FULFILLED";
export const HIDE_WARNING = "HIDE_WARNING";
export const GET_POST_ADDED_ACTION = "GET_POST_ADDED_ACTION";
export const WATCH_GUEST_ADDED_EVENT = "WATCH_GUEST_ADDED_EVENT";
